export const routes = {
  server: {
    root: import.meta.env.VITE_API_URL || "http://localhost:6060",
    login: "/api/login",
    register: "/api/register",
    forgot_password: "/api/forgot_password",
    reset_password: "/api/reset_password",
    account_activation: "/api/account_activation",
    resend_activation: "/api/resend_activation",
    refresh_token: "/api/refresh_token",
    logout: "/api/logout",
    chat: "/api/chat",
    send_contact_request: "/api/send_contact_request",
    contact_list: "/api/contact_list",
    decline_contact_request: "/api/decline_contact_request",
    accept_contact_request: "/api/accept_contact_request",
    block_contact: "/api/block_contact",
    unblock_contact: "/api/unblock_contact",
    remove_contact: "/api/remove_contact",
    upload_profile_picture:"/api/upload_profile_picture",
    profile_picture: "/api/profile_picture",
    change_username: "/api/change_username",
    change_password: "/api/change_password",
    change_email: "/api/change_email",
    send_message: "/api/send_message",
    delete_message: "/api/delete_message",
    edit_message: "/api/edit_message",
    message_list: "/api/message_list",
    user: "/api/user",
    conversation_status: "/api/conversation_status"
  },
  client: {
    chat: "/chat",
    login: "/login",
    register: "/register",
    account_activation: "/account_activation/:token",
    resend_activation: "/resend_activation",
    profile: "/profile",
    reset_password: "/reset_password/:token",
    forgot_password: "/forgot_password",
    upload_profile_picture:"/upload_profile_picture",
    change_username: "/change_username",
    change_password: "/change_password",
    change_email: "/change_email",
  },
};
